- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: бумажный принтер (машинная плата)
  description: Печатна плата для бумажного принтера.
  components:
  - type: MachineBoard
    prototype: PrinterDoc
    requirements:
      MatterBin: 3
      Manipulator: 1
    materialRequirements:
      Glass: 1

- type: entity
  id: ReflectorBoxMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Отражатель, тип "Коробка" - Машинная плата
  description: Машинная плата отражателя, тип "Коробка"
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: power_mod
  - type: MachineBoard
    prototype: ReflectorBox
    stackRequirements:
      Capacitor: 1
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 4
        defaultPrototype: PowerCellSmall

- type: entity
  id: ReflectorCornerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Отражатель, тип "Угловой"
  description: Машинная плата отражателя, тип "Угловой"
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: power_mod
  - type: MachineBoard
    prototype: ReflectorCorner
    stackRequirements:
      Capacitor: 1
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 4
        defaultPrototype: PowerCellSmall

- type: entity
  id: ReflectorCornerTsideMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Отражатель, тип "Двойной-Угловой"
  description: Машинная плата отражателя, тип "Двойной-Угловой"
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: power_mod
  - type: MachineBoard
    prototype: ReflectoCornerTside
    stackRequirements:
      Capacitor: 1
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 4
        defaultPrototype: PowerCellSmall

